- name: Install Docker on remote ubuntu host
  hosts: ubuntu
  become: true
  tasks:
    - name: Update repos and install prerequisite packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add the GPG key for the official Docker repository
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add the Docker repository to APT sources
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable"
        filename: docker # слишком большое страшное название выходит без параметра этого
        state: present

    - name: Install Docker
      apt:
        pkg:
          - docker-ce 
        update_cache: yes

    - name: Add current user to docker group
      ansible.builtin.user:
        name: "{{ansible_user}}"
        append: yes
        groups: docker

    - name: Enabling docker service
      systemd_service:
        name: docker.service
        enabled: true
        state: started

    - name: Check Docker 
      command: docker --version
      register: docker_version
      changed_when: false

    - name: Print Docker version
      debug:
        msg: "Docker version: {{docker_version.stdout}}"

