- name: Start python script in Docker 
  hosts: ubuntu 
  tasks:
    - name: Ensure /tmp/script/ exists
      file:
        path: /tmp/script/
        state: directory
        mode: 0755

    - name: Copy files to host
      copy:
        src: "{{item}}"
        dest: /tmp/script/
        owner: "{{ansible_user}}"
        mode: 0644
      with_fileglob:
        - "./files/*"

    - name: Build Docker image
      command:
        cmd: docker build -t python-requests /tmp/script/
      register: build
      failed_when: build.rc != 0
      changed_when: true

    - name: Remove previous container if exists
      shell: |
        docker rm -f python-requests || true
      changed_when: false

    - name: Run Docker container with python script
      command:
        cmd: docker run -d --name python-requests python-requests
      register: run
      failed_when: run.rc != 0
      changed_when: true

    - name: Wait for container to finish work
      command:
        cmd:
          docker wait python-requests
      register: wait
      changed_when: false
    
    - name: Check execution code for fail
      fail:
        msg: "Script exited with code {{wait.stdout}}"
      when: wait.stdout != "0"

    - name: Check docker logs
      command:
        cmd: docker logs python-requests
      register: logs
      changed_when: false

    - name: Print logs
      debug:
        msg: "{{logs.stdout}}"

